create type "public"."chart_type" as enum ('histogram', 'pie-chart', 'bar-chart', 'line-chart');

create table "public"."quiz_instance" (
    "created_at" timestamp with time zone not null default now(),
    "seconds_per_question" bigint not null,
    "author_email" text not null,
    "self_test" boolean not null default false,
    "show_results" boolean default false,
    "id" uuid not null default gen_random_uuid()
);


create table "public"."quiz_instance_pass" (
    "created_at" timestamp with time zone not null default now(),
    "passer_name" text not null,
    "quiz_instance_id" uuid default gen_random_uuid(),
    "end" timestamp with time zone,
    "start" timestamp with time zone,
    "id" uuid not null default gen_random_uuid(),
    "sets_correct_percentage" jsonb,
    "types_correct_percentage" jsonb,
    "total_correct_percentage" double precision,
    "taken_time" double precision
);


create table "public"."quiz_instance_pass_answer" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "quiz_question_id" bigint not null,
    "quiz_question_answer_id" bigint,
    "quiz_instance_pass_id" uuid
);


create table "public"."quiz_instance_set" (
    "quiz_instance_id" uuid not null,
    "quiz_set_id" bigint not null
);


create table "public"."quiz_question" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "text" text not null,
    "type" chart_type not null default 'histogram'::chart_type,
    "image_url" text
);


alter table "public"."quiz_question" enable row level security;

create table "public"."quiz_question_answer" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "text" text not null,
    "quiz_question_id" bigint,
    "is_correct" boolean not null default false
);


alter table "public"."quiz_question_answer" enable row level security;

create table "public"."quiz_set" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."quiz_set" enable row level security;

create table "public"."quiz_set_question" (
    "quiz_set_id" bigint not null,
    "quiz_question_id" bigint not null
);


alter table "public"."quiz_set_question" enable row level security;

CREATE UNIQUE INDEX "quiz-question_pkey" ON public.quiz_question USING btree (id);

CREATE UNIQUE INDEX "quiz-set_pkey" ON public.quiz_set USING btree (id);

CREATE UNIQUE INDEX quiz_instance_pass_answer_pkey ON public.quiz_instance_pass_answer USING btree (id);

CREATE UNIQUE INDEX quiz_instance_pass_duplicate_id_key ON public.quiz_instance_pass USING btree (id);

CREATE UNIQUE INDEX quiz_instance_pass_pkey ON public.quiz_instance_pass USING btree (id);

CREATE UNIQUE INDEX quiz_instance_pkey ON public.quiz_instance USING btree (id);

CREATE UNIQUE INDEX quiz_instance_set_pkey ON public.quiz_instance_set USING btree (quiz_instance_id, quiz_set_id);

CREATE UNIQUE INDEX quiz_question_answer_pkey ON public.quiz_question_answer USING btree (id);

CREATE UNIQUE INDEX quiz_set_question_pkey ON public.quiz_set_question USING btree (quiz_set_id, quiz_question_id);

alter table "public"."quiz_instance" add constraint "quiz_instance_pkey" PRIMARY KEY using index "quiz_instance_pkey";

alter table "public"."quiz_instance_pass" add constraint "quiz_instance_pass_pkey" PRIMARY KEY using index "quiz_instance_pass_pkey";

alter table "public"."quiz_instance_pass_answer" add constraint "quiz_instance_pass_answer_pkey" PRIMARY KEY using index "quiz_instance_pass_answer_pkey";

alter table "public"."quiz_instance_set" add constraint "quiz_instance_set_pkey" PRIMARY KEY using index "quiz_instance_set_pkey";

alter table "public"."quiz_question" add constraint "quiz-question_pkey" PRIMARY KEY using index "quiz-question_pkey";

alter table "public"."quiz_question_answer" add constraint "quiz_question_answer_pkey" PRIMARY KEY using index "quiz_question_answer_pkey";

alter table "public"."quiz_set" add constraint "quiz-set_pkey" PRIMARY KEY using index "quiz-set_pkey";

alter table "public"."quiz_set_question" add constraint "quiz_set_question_pkey" PRIMARY KEY using index "quiz_set_question_pkey";

alter table "public"."quiz_instance_pass" add constraint "quiz_instance_pass_duplicate_id_key" UNIQUE using index "quiz_instance_pass_duplicate_id_key";

alter table "public"."quiz_instance_pass" add constraint "quiz_instance_pass_duplicate_quiz_instance_id_fkey" FOREIGN KEY (quiz_instance_id) REFERENCES quiz_instance(id) not valid;

alter table "public"."quiz_instance_pass" validate constraint "quiz_instance_pass_duplicate_quiz_instance_id_fkey";

alter table "public"."quiz_instance_pass_answer" add constraint "quiz_instance_pass_answer_quiz_instance_pass_id_fkey" FOREIGN KEY (quiz_instance_pass_id) REFERENCES quiz_instance_pass(id) not valid;

alter table "public"."quiz_instance_pass_answer" validate constraint "quiz_instance_pass_answer_quiz_instance_pass_id_fkey";

alter table "public"."quiz_instance_pass_answer" add constraint "quiz_instance_pass_answer_quiz_question_answer_id_fkey" FOREIGN KEY (quiz_question_answer_id) REFERENCES quiz_question_answer(id) not valid;

alter table "public"."quiz_instance_pass_answer" validate constraint "quiz_instance_pass_answer_quiz_question_answer_id_fkey";

alter table "public"."quiz_instance_pass_answer" add constraint "quiz_instance_pass_answer_quiz_question_id_fkey" FOREIGN KEY (quiz_question_id) REFERENCES quiz_question(id) not valid;

alter table "public"."quiz_instance_pass_answer" validate constraint "quiz_instance_pass_answer_quiz_question_id_fkey";

alter table "public"."quiz_instance_set" add constraint "quiz_instance_set_quiz_instance_id_fkey" FOREIGN KEY (quiz_instance_id) REFERENCES quiz_instance(id) ON DELETE CASCADE not valid;

alter table "public"."quiz_instance_set" validate constraint "quiz_instance_set_quiz_instance_id_fkey";

alter table "public"."quiz_instance_set" add constraint "quiz_instance_set_quiz_set_id_fkey" FOREIGN KEY (quiz_set_id) REFERENCES quiz_set(id) ON DELETE CASCADE not valid;

alter table "public"."quiz_instance_set" validate constraint "quiz_instance_set_quiz_set_id_fkey";

alter table "public"."quiz_question_answer" add constraint "quiz_question_answer_quiz_question_id_fkey" FOREIGN KEY (quiz_question_id) REFERENCES quiz_question(id) ON DELETE CASCADE not valid;

alter table "public"."quiz_question_answer" validate constraint "quiz_question_answer_quiz_question_id_fkey";

alter table "public"."quiz_set_question" add constraint "quiz_set_question_quiz_question_id_fkey" FOREIGN KEY (quiz_question_id) REFERENCES quiz_question(id) ON DELETE CASCADE not valid;

alter table "public"."quiz_set_question" validate constraint "quiz_set_question_quiz_question_id_fkey";

alter table "public"."quiz_set_question" add constraint "quiz_set_question_quiz_set_id_fkey" FOREIGN KEY (quiz_set_id) REFERENCES quiz_set(id) ON DELETE CASCADE not valid;

alter table "public"."quiz_set_question" validate constraint "quiz_set_question_quiz_set_id_fkey";

grant delete on table "public"."quiz_instance" to "anon";

grant insert on table "public"."quiz_instance" to "anon";

grant references on table "public"."quiz_instance" to "anon";

grant select on table "public"."quiz_instance" to "anon";

grant trigger on table "public"."quiz_instance" to "anon";

grant truncate on table "public"."quiz_instance" to "anon";

grant update on table "public"."quiz_instance" to "anon";

grant delete on table "public"."quiz_instance" to "authenticated";

grant insert on table "public"."quiz_instance" to "authenticated";

grant references on table "public"."quiz_instance" to "authenticated";

grant select on table "public"."quiz_instance" to "authenticated";

grant trigger on table "public"."quiz_instance" to "authenticated";

grant truncate on table "public"."quiz_instance" to "authenticated";

grant update on table "public"."quiz_instance" to "authenticated";

grant delete on table "public"."quiz_instance" to "service_role";

grant insert on table "public"."quiz_instance" to "service_role";

grant references on table "public"."quiz_instance" to "service_role";

grant select on table "public"."quiz_instance" to "service_role";

grant trigger on table "public"."quiz_instance" to "service_role";

grant truncate on table "public"."quiz_instance" to "service_role";

grant update on table "public"."quiz_instance" to "service_role";

grant delete on table "public"."quiz_instance_pass" to "anon";

grant insert on table "public"."quiz_instance_pass" to "anon";

grant references on table "public"."quiz_instance_pass" to "anon";

grant select on table "public"."quiz_instance_pass" to "anon";

grant trigger on table "public"."quiz_instance_pass" to "anon";

grant truncate on table "public"."quiz_instance_pass" to "anon";

grant update on table "public"."quiz_instance_pass" to "anon";

grant delete on table "public"."quiz_instance_pass" to "authenticated";

grant insert on table "public"."quiz_instance_pass" to "authenticated";

grant references on table "public"."quiz_instance_pass" to "authenticated";

grant select on table "public"."quiz_instance_pass" to "authenticated";

grant trigger on table "public"."quiz_instance_pass" to "authenticated";

grant truncate on table "public"."quiz_instance_pass" to "authenticated";

grant update on table "public"."quiz_instance_pass" to "authenticated";

grant delete on table "public"."quiz_instance_pass" to "service_role";

grant insert on table "public"."quiz_instance_pass" to "service_role";

grant references on table "public"."quiz_instance_pass" to "service_role";

grant select on table "public"."quiz_instance_pass" to "service_role";

grant trigger on table "public"."quiz_instance_pass" to "service_role";

grant truncate on table "public"."quiz_instance_pass" to "service_role";

grant update on table "public"."quiz_instance_pass" to "service_role";

grant delete on table "public"."quiz_instance_pass_answer" to "anon";

grant insert on table "public"."quiz_instance_pass_answer" to "anon";

grant references on table "public"."quiz_instance_pass_answer" to "anon";

grant select on table "public"."quiz_instance_pass_answer" to "anon";

grant trigger on table "public"."quiz_instance_pass_answer" to "anon";

grant truncate on table "public"."quiz_instance_pass_answer" to "anon";

grant update on table "public"."quiz_instance_pass_answer" to "anon";

grant delete on table "public"."quiz_instance_pass_answer" to "authenticated";

grant insert on table "public"."quiz_instance_pass_answer" to "authenticated";

grant references on table "public"."quiz_instance_pass_answer" to "authenticated";

grant select on table "public"."quiz_instance_pass_answer" to "authenticated";

grant trigger on table "public"."quiz_instance_pass_answer" to "authenticated";

grant truncate on table "public"."quiz_instance_pass_answer" to "authenticated";

grant update on table "public"."quiz_instance_pass_answer" to "authenticated";

grant delete on table "public"."quiz_instance_pass_answer" to "service_role";

grant insert on table "public"."quiz_instance_pass_answer" to "service_role";

grant references on table "public"."quiz_instance_pass_answer" to "service_role";

grant select on table "public"."quiz_instance_pass_answer" to "service_role";

grant trigger on table "public"."quiz_instance_pass_answer" to "service_role";

grant truncate on table "public"."quiz_instance_pass_answer" to "service_role";

grant update on table "public"."quiz_instance_pass_answer" to "service_role";

grant delete on table "public"."quiz_instance_set" to "anon";

grant insert on table "public"."quiz_instance_set" to "anon";

grant references on table "public"."quiz_instance_set" to "anon";

grant select on table "public"."quiz_instance_set" to "anon";

grant trigger on table "public"."quiz_instance_set" to "anon";

grant truncate on table "public"."quiz_instance_set" to "anon";

grant update on table "public"."quiz_instance_set" to "anon";

grant delete on table "public"."quiz_instance_set" to "authenticated";

grant insert on table "public"."quiz_instance_set" to "authenticated";

grant references on table "public"."quiz_instance_set" to "authenticated";

grant select on table "public"."quiz_instance_set" to "authenticated";

grant trigger on table "public"."quiz_instance_set" to "authenticated";

grant truncate on table "public"."quiz_instance_set" to "authenticated";

grant update on table "public"."quiz_instance_set" to "authenticated";

grant delete on table "public"."quiz_instance_set" to "service_role";

grant insert on table "public"."quiz_instance_set" to "service_role";

grant references on table "public"."quiz_instance_set" to "service_role";

grant select on table "public"."quiz_instance_set" to "service_role";

grant trigger on table "public"."quiz_instance_set" to "service_role";

grant truncate on table "public"."quiz_instance_set" to "service_role";

grant update on table "public"."quiz_instance_set" to "service_role";

grant delete on table "public"."quiz_question" to "anon";

grant insert on table "public"."quiz_question" to "anon";

grant references on table "public"."quiz_question" to "anon";

grant select on table "public"."quiz_question" to "anon";

grant trigger on table "public"."quiz_question" to "anon";

grant truncate on table "public"."quiz_question" to "anon";

grant update on table "public"."quiz_question" to "anon";

grant delete on table "public"."quiz_question" to "authenticated";

grant insert on table "public"."quiz_question" to "authenticated";

grant references on table "public"."quiz_question" to "authenticated";

grant select on table "public"."quiz_question" to "authenticated";

grant trigger on table "public"."quiz_question" to "authenticated";

grant truncate on table "public"."quiz_question" to "authenticated";

grant update on table "public"."quiz_question" to "authenticated";

grant delete on table "public"."quiz_question" to "service_role";

grant insert on table "public"."quiz_question" to "service_role";

grant references on table "public"."quiz_question" to "service_role";

grant select on table "public"."quiz_question" to "service_role";

grant trigger on table "public"."quiz_question" to "service_role";

grant truncate on table "public"."quiz_question" to "service_role";

grant update on table "public"."quiz_question" to "service_role";

grant delete on table "public"."quiz_question_answer" to "anon";

grant insert on table "public"."quiz_question_answer" to "anon";

grant references on table "public"."quiz_question_answer" to "anon";

grant select on table "public"."quiz_question_answer" to "anon";

grant trigger on table "public"."quiz_question_answer" to "anon";

grant truncate on table "public"."quiz_question_answer" to "anon";

grant update on table "public"."quiz_question_answer" to "anon";

grant delete on table "public"."quiz_question_answer" to "authenticated";

grant insert on table "public"."quiz_question_answer" to "authenticated";

grant references on table "public"."quiz_question_answer" to "authenticated";

grant select on table "public"."quiz_question_answer" to "authenticated";

grant trigger on table "public"."quiz_question_answer" to "authenticated";

grant truncate on table "public"."quiz_question_answer" to "authenticated";

grant update on table "public"."quiz_question_answer" to "authenticated";

grant delete on table "public"."quiz_question_answer" to "service_role";

grant insert on table "public"."quiz_question_answer" to "service_role";

grant references on table "public"."quiz_question_answer" to "service_role";

grant select on table "public"."quiz_question_answer" to "service_role";

grant trigger on table "public"."quiz_question_answer" to "service_role";

grant truncate on table "public"."quiz_question_answer" to "service_role";

grant update on table "public"."quiz_question_answer" to "service_role";

grant delete on table "public"."quiz_set" to "anon";

grant insert on table "public"."quiz_set" to "anon";

grant references on table "public"."quiz_set" to "anon";

grant select on table "public"."quiz_set" to "anon";

grant trigger on table "public"."quiz_set" to "anon";

grant truncate on table "public"."quiz_set" to "anon";

grant update on table "public"."quiz_set" to "anon";

grant delete on table "public"."quiz_set" to "authenticated";

grant insert on table "public"."quiz_set" to "authenticated";

grant references on table "public"."quiz_set" to "authenticated";

grant select on table "public"."quiz_set" to "authenticated";

grant trigger on table "public"."quiz_set" to "authenticated";

grant truncate on table "public"."quiz_set" to "authenticated";

grant update on table "public"."quiz_set" to "authenticated";

grant delete on table "public"."quiz_set" to "service_role";

grant insert on table "public"."quiz_set" to "service_role";

grant references on table "public"."quiz_set" to "service_role";

grant select on table "public"."quiz_set" to "service_role";

grant trigger on table "public"."quiz_set" to "service_role";

grant truncate on table "public"."quiz_set" to "service_role";

grant update on table "public"."quiz_set" to "service_role";

grant delete on table "public"."quiz_set_question" to "anon";

grant insert on table "public"."quiz_set_question" to "anon";

grant references on table "public"."quiz_set_question" to "anon";

grant select on table "public"."quiz_set_question" to "anon";

grant trigger on table "public"."quiz_set_question" to "anon";

grant truncate on table "public"."quiz_set_question" to "anon";

grant update on table "public"."quiz_set_question" to "anon";

grant delete on table "public"."quiz_set_question" to "authenticated";

grant insert on table "public"."quiz_set_question" to "authenticated";

grant references on table "public"."quiz_set_question" to "authenticated";

grant select on table "public"."quiz_set_question" to "authenticated";

grant trigger on table "public"."quiz_set_question" to "authenticated";

grant truncate on table "public"."quiz_set_question" to "authenticated";

grant update on table "public"."quiz_set_question" to "authenticated";

grant delete on table "public"."quiz_set_question" to "service_role";

grant insert on table "public"."quiz_set_question" to "service_role";

grant references on table "public"."quiz_set_question" to "service_role";

grant select on table "public"."quiz_set_question" to "service_role";

grant trigger on table "public"."quiz_set_question" to "service_role";

grant truncate on table "public"."quiz_set_question" to "service_role";

grant update on table "public"."quiz_set_question" to "service_role";

create policy "Enable insert for all users"
on "public"."quiz_instance"
as permissive
for insert
to public
with check (true);


create policy "Enable read access for all users"
on "public"."quiz_question"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."quiz_question_answer"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."quiz_set"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."quiz_set_question"
as permissive
for select
to public
using (true);



